version: '3.8'
services:
  backend:
    container_name: express-backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - '5001:5001'
    command: node index.js
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres_store
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=online_store
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5556:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
